repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        # files: ^api/.*\.(py)$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: isort --check --diff
        # files: ^api/.*\.(py)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^client/.*\.(ts|tsx|js|css|html)$
        args:
          [
            '--config=./client/.prettierrc',
            '--ignore-path=./client/.prettierignore'
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.40.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - '@next/eslint-plugin-next'
          - eslint-config-standard-with-typescript
          - eslint-config-react-app
          - typescript
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-config-prettier
          - eslint-plugin-jsx-a11y
          - eslint-plugin-import
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - eslint-plugin-n
          - eslint-plugin-promise
          # - next/babel
        files: ^client/.*\.(ts|tsx|js|css|html)$
        types: [file]
        args:
          [
            '--config=./client/.eslintrc.json',
            '--ignore-path=./client/.eslintignore'
          ]
