# Generated by Django 4.1.7 on 2023-06-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_course', to='app_sph_lms.course'),
        ),
        migrations.AlterField(
            model_name='learningpathcourse',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_course', to='app_sph_lms.learningpath'),
        ),
    ]
