# Generated by Django 4.1.7 on 2023-03-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.status'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.status'),
        ),
    ]
