# Generated by Django 4.1.7 on 2023-03-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.class'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sph_lms.class'),
        ),
        migrations.AlterUniqueTogether(
            name='trainee',
            unique_together={('company', 'trainee')},
        ),
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('company', 'trainer')},
        ),
    ]
