# Generated by Django 4.1.7 on 2023-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0002_alter_trainee_status_alter_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
