# Generated by Django 4.1.7 on 2023-05-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0002_materialcategory_material_companymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_materials', to='app_sph_lms.company'),
        ),
    ]
