# Generated by Django 4.2.2 on 2023-07-14 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'app_sph_lms',
            '0002_alter_course_image_alter_learningpath_image_and_more'
        )
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)]
            )
        ),
    ]
