# Generated by Django 4.1.7 on 2023-06-15 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0003_rename_img_path_user_image_remove_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='company',
        ),
        migrations.AddField(
            model_name='course',
            name='trainee',
            field=models.ManyToManyField(limit_choices_to={'is_trainer': False}, related_name='enrolled_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
