# Generated by Django 4.1.7 on 2023-06-02 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0006_learningpath_alter_course_author_learningpathcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
