# Generated by Django 4.1.7 on 2023-06-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0006_learningpath_rename_img_path_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL),
        ),
    ]
