# Generated by Django 4.1.7 on 2023-06-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0007_alter_learningpath_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='img_path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preview_vid_path',
        ),
    ]
