# Generated by Django 4.1.7 on 2023-06-09 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0007_alter_learningpath_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='learningpath',
            name='trainee',
            field=models.ManyToManyField(related_name='enrolled_learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='categories', through='app_sph_lms.CourseCategory', to='app_sph_lms.category'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
